### ISSUE TITLE
RFE 

### ISSUE THREAD

**Issue by l-g** [DaWe35/Facebook-event-crawler#1]
Here are two use cases I was wondering if you maybe could take under consideration?

1. On Thursday I have 12 events between 17:00 and 22:00 (I live in a city) all over the city. It would be great if they could be displayed on a map so I could "plan my route" easier. In other words, if this crawler could extract the address of all my upcoming events and display them on a map? Or maybe even easier, just extract the location and format it in a way that Google Map can import? (A shortcut would be to just concatenate strings to build the URL string for Google maps, like this example https://www.google.com/maps/dir/Amazon+Go,+7th+Avenue,+Seattle,+Washington,+USA/Seattle,+Washington,+USA/Boeing+Everett+Factory,+West+Casino+Road,+Everett,+Washington,+USA/Microsoft+Building+92,+Northeast+36th+Street,+Redmond,+Washington,+USA/@47.7679854,-122.3785765,11z - as you can see, the format is pretty straightforward)

2. There are also those events listed under _Discover_. Would be nice if these could be displayed on a map in a similar way to (1), including filters (art, sport, music etc) so you easily can find a nearby event if you are looking for something to do

**Comment by DaWe35** [comment]
Hey!

Thank you for your question, here are my answers:

1. As you can see on the [picture](https://raw.githubusercontent.com/DaWe35/Facebook-event-crawler/master/database.jpg), the crawler tries to get the coordinates (latitude and longitude) of the event and writes out to the database (lat & lon columns). After _Facebook-event-crawler_ created the database, you can easily create a map with markers. Here are the examples: [Lealet with Open Street map](https://leafletjs.com) or [Google maps](https://stackoverflow.com/a/3059129/8474284)

2. Yeah, that would be a cool feature. I think you need to add new columns to the database to store filters because you can run _Facebook-event-crawler_ twice with other filters, and there will be a mixed database. So you just need to separate every search by saving the filters also.
